name: InfernumPvP
version: 1.0
main: net.apartium.servers.infernumpvp.InfernumPvP
authors: [xShakedDev, Voigon]
commands:
  infernum:
    description: /infernum <kit> <player>
  coins:
    description: /coins <player>
  spawn:
    description: /spawn
  test:
    description: test command
  report:
    description: report
  ovo:
    description: onevsone
  break:
    description: allow break and disallow